#!/usr/bin/env python3
"""Generate cloudformation/www-redirect.yaml from hosts.txt.

For each state host X (e.g. mn.db101.org, preview-mn.db101.org, mn.hb101.org) emit:
  - ACM cert SAN  www.X   (+ a DNS-validation entry in X's hosted zone)
  - CloudFront alias  www.X
  - Route53 CNAME  www.X -> the redirect distribution   (UPSERT: adopts the current
    www.X -> s6 records, or creates missing ones)
A single generic strip-`www` CloudFront Function 301s www.X -> https://X<uri><qs>.

Edit hosts.txt, run this, then `deploy-stack.ps1 www-redirect`.
"""
import os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT  = os.path.join(HERE, "..", "www-redirect.yaml")

ZONES = {                       # zone-apex -> Route53 hosted zone id
    "db101.org": "Z3T3K8XH9ZMBIW",
    "hb101.org": "Z26W7416MQ6FIP",
}
CF_HOSTED_ZONE = "Z2FDTNDATAQYW2"   # fixed CloudFront alias zone (unused: we CNAME)

def zone_of(host):
    for apex, zid in ZONES.items():
        if host == apex or host.endswith("." + apex):
            return apex, zid
    raise SystemExit(f"host not in a known zone: {host}")

def load_hosts():
    hosts = []
    with open(os.path.join(HERE, "hosts.txt"), encoding="utf-8") as f:
        for line in f:
            s = line.strip()
            if not s or s.startswith("#"):
                continue
            hosts.append(s)
    # de-dup, stable order
    seen, out = set(), []
    for h in hosts:
        if h not in seen:
            seen.add(h); out.append(h)
    return out

def main():
    hosts = load_hosts()
    wwws  = [f"www.{h}" for h in hosts]
    primary, sans = wwws[0], wwws[1:]

    L = []
    w = L.append
    w("# GENERATED by cloudformation/www-redirect/generate.py from hosts.txt — DO NOT EDIT BY HAND.")
    w("# Add/remove states in hosts.txt, re-run generate.py, then deploy-stack.ps1 www-redirect.")
    w("AWSTemplateFormatVersion: '2010-09-09'")
    w("Description: >-")
    w("  Reflexive-www redirect: 301 www.<state>.db101.org / www.<state>.hb101.org (and preview-)")
    w("  to the bare host over HTTPS. Fixes the non-bypassable HSTS+cert dead-end that hits users")
    w("  and clients who reflexively prepend 'www.' to a double-label host. us-east-1.")
    w("")
    w("Resources:")
    # --- strip-www function ---
    w("  StripWwwFunction:")
    w("    Type: AWS::CloudFront::Function")
    w("    Properties:")
    w("      Name: www-redirect-strip-www")
    w("      AutoPublish: true")
    w("      FunctionConfig:")
    w("        Comment: 301 www.<host> -> https://<host> (strip leading www.), preserving path+query")
    w("        Runtime: cloudfront-js-2.0")
    w("      FunctionCode: |")
    w("        function handler(event) {")
    w("          var req = event.request;")
    w("          var host = req.headers.host.value;")
    w("          var target = host.indexOf('www.') === 0 ? host.slice(4) : host;")
    w("          var qs = '';")
    w("          for (var k in req.querystring) {")
    w("            qs += (qs ? '&' : '?') + k + (req.querystring[k].value ? '=' + req.querystring[k].value : '');")
    w("          }")
    w("          return {")
    w("            statusCode: 301,")
    w("            statusDescription: 'Moved Permanently',")
    w("            headers: { 'location': { value: 'https://' + target + req.uri + qs } }")
    w("          };")
    w("        }")
    # --- cert ---
    w("  Cert:")
    w("    Type: AWS::CertificateManager::Certificate")
    w("    Properties:")
    w(f"      DomainName: {primary}")
    w("      ValidationMethod: DNS")
    w("      SubjectAlternativeNames:")
    for s in sans:
        w(f"        - {s}")
    w("      DomainValidationOptions:")
    for wn, h in zip(wwws, hosts):
        _, zid = zone_of(h)
        w(f"        - DomainName: {wn}")
        w(f"          HostedZoneId: {zid}")
    # --- distribution ---
    w("  Distribution:")
    w("    Type: AWS::CloudFront::Distribution")
    w("    Properties:")
    w("      DistributionConfig:")
    w("        Enabled: true")
    w("        Comment: reflexive-www redirect")
    w("        IPV6Enabled: true")
    w("        HttpVersion: http2and3")
    w("        PriceClass: PriceClass_100")
    w("        Aliases:")
    for wn in wwws:
        w(f"          - {wn}")
    w("        ViewerCertificate:")
    w("          AcmCertificateArn: !Ref Cert")
    w("          SslSupportMethod: sni-only")
    w("          MinimumProtocolVersion: TLSv1.2_2021")
    w("        Origins:")
    w("          - Id: blackhole")
    w("            DomainName: www.db101.org   # never contacted: the function 301s at viewer-request")
    w("            CustomOriginConfig:")
    w("              OriginProtocolPolicy: https-only")
    w("        DefaultCacheBehavior:")
    w("          TargetOriginId: blackhole")
    w("          ViewerProtocolPolicy: redirect-to-https")
    w("          AllowedMethods: [GET, HEAD]")
    w("          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad   # Managed-CachingDisabled")
    w("          FunctionAssociations:")
    w("            - EventType: viewer-request")
    w("              FunctionARN: !GetAtt StripWwwFunction.FunctionMetadata.FunctionARN")
    # --- route53 record groups, one per zone ---
    # SANs + aliases above always cover the FULL host list (so the cert issues once and never
    # replaces during a staged rollout). Records can be staged to a subset via ACTIVE=<comma-list>
    # for a canary; ACTIVE unset/empty => all hosts. Canary flow: ACTIVE=mn.db101.org,preview-mn...
    # generate+deploy, test, then re-generate with ACTIVE unset and deploy the rest (no cert change).
    active_env = os.environ.get("ACTIVE", "").strip()
    active = set(x.strip() for x in active_env.split(",") if x.strip()) if active_env else set(hosts)
    unknown = active - set(hosts)
    if unknown:
        raise SystemExit(f"ACTIVE lists hosts not in hosts.txt: {sorted(unknown)}")
    if active_env:
        print(f"  (records staged to ACTIVE subset: {sorted(active)})")
    by_zone = {}
    for h, wn in zip(hosts, wwws):
        if h not in active:
            continue
        apex, zid = zone_of(h)
        by_zone.setdefault((apex, zid), []).append(wn)
    for i, ((apex, zid), names) in enumerate(sorted(by_zone.items())):
        res = "RecordsDb101" if apex == "db101.org" else "RecordsHb101"
        w(f"  {res}:")
        w("    Type: AWS::Route53::RecordSetGroup")
        w("    Properties:")
        w(f"      HostedZoneId: {zid}   # {apex}")
        w("      RecordSets:")
        for wn in names:
            w(f"        - Name: {wn}")
            w("          Type: CNAME")
            w("          TTL: 300")
            w("          ResourceRecords:")
            w("            - !GetAtt Distribution.DomainName")
    w("")
    w("Outputs:")
    w("  DistributionDomain:")
    w("    Value: !GetAtt Distribution.DomainName")
    w("  CertArn:")
    w("    Value: !Ref Cert")
    w("  HostCount:")
    w(f"    Value: '{len(hosts)}'")
    w("")

    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(L))
    print(f"wrote {OUT} for {len(hosts)} hosts ({len(wwws)} SANs)")

if __name__ == "__main__":
    main()
